apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: select-field-from-api-debug
  title: Debugging SelectFieldFromApi
  description: "Debugging complex filters on SelectFieldFromApi scaffolder extension"
spec:
  type: service
  owner: user:guest
  parameters:
    - title: Basic details
      name:
        title: Group
        type: string
        description: Group
        ui:field: SelectFieldFromApi
        ui:options:
          path: "catalog/entities"
          params:
            filter: "kind=Group"
          valueSelector: "metadata.name"
          labelSelector: "metadata.description"
    - title: Advanced options
      properties:
        system:
          title: System
          type: string
          description: Entity Selector
          ui:field: SelectFieldFromApi
          ui:options:
            path: "catalog/entities"
            params:
              filter: "kind=system,spec.owner={{ parameters.delivery_stream }}&filter=kind=system,spec.owner=application-platforms"
            valueSelector: "metadata.name"
            labelSelector: "metadata.description"
  steps:
    - id: log-message
      name: Log Message
      action: debug:log
      input:
        listWorkspace: true
