apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: custom-field-ext
  title: Custom Field Extension Example
  description: "A Scaffolder template with custom field extension"
spec:
  type: service
  owner: user:guest
  parameters:
    - title: Provide some simple information
      properties:
        text:
          title: some text
          type: string
        name:
          title: AWS Policies thing
          type: string
          description: My custom name for the component
          ui:field: AwsManagedPoliciesFieldExtension
  steps:
    - id: log-message
      name: Log Message
      action: debug:log
      input:
        listWorkspace: true
